---
title: "Stats 531 (Winter 2018) <br>'Analysis of Time Series'"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    theme: flatly
    toc: yes
csl: ecology.csl
---

------

## Course description

This course gives an introduction to time series analysis using
time domain methods and frequency domain methods. The goal is to
acquire the theoretical and computational skills required to investigate
data collected as a time series. The first half of the course will develop 
classical time series methodology, including auto-regressive moving average (ARMA) models, regression with ARMA errors, and estimation of the spectral density.
The second half of the course will focus on state space model techniques for fitting structured dynamic models to time series data. We will progress from fitting linear, Gaussian dynamic models to fitting nonlinear models for which Monte Carlo methods are required.
Examples will be drawn from ecology, economics, epidemiology, finance and elsewhere.

--------------

## Course information

* Class meets Mon/Wed 10:00-11:30 in 1427 Mason Hall

* Contact information:
    + Office: 453 West Hall 
    + Phone: 647 5457 
    + E-mail: ionides@umich.edu 
    + Web: dept.stat.lsa.umich.edu/~ionides
    + Office hours: Monday 4-5pm, Wednesday 3-4pm
* GSI: Joonha Park
    + Office hours: Friday 9:30-11am in 2165 USB.
    + Computing support: inquire by email, with a detailed description of the problem, what you did, and what error message you obtained.
    + E-mail: joonhap@umich.edu
* Textbook: R. Shumway and D. Stoffer "Time Series Analysis and its Applications" 4th edition. 
A pdf is available using the UM Library's Springer subscription.
An updated pdf is available free from [David Stoffer's website](http://www.stat.pitt.edu/stoffer/tsa4/tsa4.pdf)
* Pre-requisites:
    + Theoretical statistics. STATS 426 or equivalent. For review, see "Mathematical Statistics and Data Analysis" by J. A. Rice. 
    + Linear algebra. A certain amount of basic linear algebra will be required. For review, see 
[www.sosmath.com/matrix/matrix.html](http://www.sosmath.com/matrix/matrix.html).
    + R programming. There is no formal R prerequisite, but we will be working with R extensively and so you should allow extra time for this course if you are new to R programming.

-----------

##  Grading

* Weekly homeworks (20\%).
* A midterm exam (20\%, in class on Wednesday 2/21).
* A midterm project analyzing a time series of your choice using methods covered in the first half of the course (20\%, due Wednesday 3/07). 
* A final project analyzing a time series of your choice using methods covered in the entire course (40\%, due Wednesday 4/25). 

Homework will be graded on completeness. 
To get these points, the homework must include two statements titled "Sources" and "Please explain".
 
* The statement of sources must list all books, internet resources or other people consulted while completing the homework. For example, "Sources: notes only," or, "Sources: collaboration with X and Y; web site Z," or, "Sources: notes and office hours."
Any material taken from any source, such as the internet, must be properly acknowledged. 
Directly copied text must be in quotation marks.
Directly copied equations must be explicitly referenced to the source.
Unattributed copying from any source is plagiarism, and has potentially [serious consequences](http://www.rackham.umich.edu/current-students/policies/academic-policies/section11).

* The explanation request provides useful feedback for the GSI and instructor. For example, "Please explain: nothing, everything is clear," or, "Please explain: I'm having difficulties manipulating Taylor series." or, "Please explain: I had difficulty constructing the prewhitening filter. What is a good way to do that in R?"

* Homework will not be graded on correctness, to encourage independent work. The GSI may provide some feedback on correctness, but students are responsible for checking their work against posted solutions.

* The midterm and final projects must take care to properly reference all sources. For projects, no specific source and explanation request statements are requested.

----------

## Class notes


1. [Introduction](01/notes01.html). [(R script)](01/notes01.R)

2. [Time series models, trend and autocovariance](02/notes02.html). [(R script)](02/notes02.R)

3. [Stationarity, white noise, and some basic time series models](03/notes03.html). [(R script)](03/notes03.R)

4. [Linear time series models and the algebra of ARMA models](04/notes04.html). [(R script)](04/notes04.R)

5. [Parameter estimation and model identification for ARMA models](05/notes05.html). [(R script)](05/notes05.R)

6. [Extending the ARMA model: Seasonality and trend](06/notes06.html). [(R script)](06/notes06.R)

7. [Introduction to the frequency domain](07/notes07.html). [(R script)](07/notes07.R)

8. [Smoothing in the time and frequency domains](08/notes08.html). [(R script)](08/notes08.R)

9. [Introduction to partially observed Markov process models](09/notes09.html). [(R script)](09/notes09.R)

10. [Statistical methodology for nonlinear partially observed Markov process models](10/notes10.html). [(R script)](10/notes10.R)

11. [Dynamic models and their simulation by Euler’s method](11/notes11.html). [(R script)](11/notes11.R)

<!--
13. [Practical likelihood-based inference for POMP models](notes13/notes13.html). [(R script)](notes13/notes13.R)

14. [POMP inference: other approaches complementing likelihood-based analysis](notes14/notes14.html). 

15. [Case study: POMP modeling to investigate financial volatility](notes15/notes15.html). [(R script)](notes15/notes15.R)

16. [Using a Linux sever for POMP analysis](notes16/linux/linux.html). [Using the UM Flux Linux cluster](notes16/flux/flux.html).

17. [Forecasting and fitted values, with a case study of Ebola](notes17/notes17.html). [(R script)](notes17/notes17.R)

18. [Time series models with covariates, and a case study of polio](notes18/notes18.html). [(R script)](notes18/notes18.R)

19. [Concluding remarks](concluding_remarks/concluding_remarks.html)

-->

--------

## Homework assignments


* [Homework 0](hw00/hw00.html), due in class on 1/10. Setting up your computational environment.

* [Homework 1](hw01/hw01.html), due in class on Wednesday 1/17.  [Solution](hw01/sol01.html).

* [Homework 2](hw02/hw02.html), due in class on Monday 1/29. [Solution](hw02/sol02.html).

* [Homework 3](hw03/hw03.html), due 11:59pm on Monday 2/5. [Solution](hw03/sol03.html).

* [Homework 4](hw04/hw04.html), to be carried out by Monday 2/12.

* [Homework 5](hw05/hw05.html), due 11:59pm on Monday 2/19. [Solution](hw05/sol05.html).

* [Homework 6](hw06/hw06.html), due in class on Wednesday 3/14. [Solution](hw06/sol06.html).

* [Homework 7](hw07/hw07.html), due 11:59pm on Monday 3/26.

* [Homework 8](hw08/hw08.html), to be carried out by Monday 4/2.

<!--
a single slide due midnight on 3/21, for a presentation in class on 3/22 or 3/24.

* [Homework 8](hw08/hw08.html), due on 3/29. [Reponses to time survey](hw/summary08.html). [Solution](hw/sol08.html).

* [Homework 9](hw09/hw09.html), due on 4/7. [Solution](hw/sol09.html).

* [Homework 10](hw10/hw10.html), due on 4/14.

-->


------------

## Midterm exam information


* The midterm exam will involve reasoning about a data analysis using the theoretical and computational techniques we have studied in class. 

* The exam may include techniques covered in homeworks and will assume familiarity with the notes.
Reading the textbook is not mandatory for the exam, but may be useful to get a broader perspective.

<!-- Any parts of the notes that are not examinable will be specified before the exam. -->

<!-- You do not need to review algebraic manipulation of state space models beyond what was in homework. -->

* You should bring to the exam just pens and/or pencils. The exam will be taken without any electronic devices, books or notes.

* The best predictor of the style of the exam is the past papers from the Winter 2016 version of this course:

    +  [Midterm exam for STATS 531 Winter 2016](exam/w16/mt531w16.pdf). [Solutions](exam/w16/mt531w16sol.pdf).

    +  [Midterm exam for STATS 531 Winter 2018](exam/w18/mt531w18.pdf). [Solutions](exam/w18/mt531w18sol.pdf).
    
-------------------

## Midterm project

* [Information](midterm_project/midterm_project_info.html)

* [Grading scheme](midterm_project/grade_scheme_midterm_project.html)

* [Projects](midterm_project/index.html)

* You're also welcome to browse previous midterm projects [available online](http://ionides.github.io/531w16/midterm_project/)

-------------

## Final project

* [Information](final_project/final_project_info.html)

* You're welcome to browse previous final projects [available online](http://ionides.github.io/531w16/final_project/)

<!--


* [Projects](final_project/index.html)

-->

---------